"""
Abstract Base Strategy & Strategy Registry.

Strategies encapsulate trading decision logic based on incoming MarketDataEvents
and produce SignalEvents.
"""

from abc import ABC, abstractmethod
from typing import Dict, List, Type
import logging

from app.core.events import MarketDataEvent, SignalEvent, FillEvent
from app.core.event_bus import EventBus

logger = logging.getLogger(__name__)


class BaseStrategy(ABC):
    """
    Abstract Base Class for all trading strategies.
    
    Subclasses must implement `on_market_data` to generate signal events when entry/exit
    rules are satisfied.
    """

    def __init__(self, strategy_id: str, symbol: str, event_bus: EventBus, config: dict):
        self.strategy_id = strategy_id
        self.symbol = symbol
        self.event_bus = event_bus
        self.config = config

    def on_start(self) -> None:
        """Called prior to starting a backtest to initialize indicators or state."""
        pass

    @abstractmethod
    def on_market_data(self, event: MarketDataEvent) -> List[SignalEvent]:
        """
        Process a new market data bar (OHLCV).
        
        Returns:
            List of generated SignalEvents (BUY, SELL, or EXIT).
        """
        pass

    def on_fill(self, event: FillEvent) -> None:
        """Callback executed when an order generated by this strategy is filled."""
        pass


class StrategyRegistry:
    """Central registry to dynamically discover and instantiate strategy classes from JSON config."""

    _registry: Dict[str, Type[BaseStrategy]] = {}

    @classmethod
    def register(cls, name: str):
        """Decorator to register strategy classes by name."""
        def decorator(subclass: Type[BaseStrategy]):
            cls._registry[name] = subclass
            return subclass
        return decorator

    @classmethod
    def get_strategy_class(cls, name: str) -> Type[BaseStrategy]:
        if name not in cls._registry:
            raise KeyError(f"Strategy '{name}' not found in registry. Registered: {list(cls._registry.keys())}")
        return cls._registry[name]
